"""
This type stub file was generated by pyright.
"""

from typing import Any, Awaitable, Callable, Optional, Union

def is_coroutine(test: Optional[Union[Awaitable[Any], Any]] = ...) -> bool:
    ...

async def execute_maybe_async_function(func: Callable[..., Any], *args: Any) -> Any:
    ...

