"""
This type stub file was generated by pyright.
"""

from polywrap_core import Client, IUriResolutionContext, IUriResolver, Uri, UriPackageOrWrapper
from polywrap_result import Result
from .types import StaticResolverLike

class StaticResolver(IUriResolver):
    __slots__ = ...
    uri_map: StaticResolverLike
    def __init__(self, uri_map: StaticResolverLike) -> None:
        ...
    
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[UriPackageOrWrapper]:
        ...
    


