"""
This type stub file was generated by pyright.
"""

from polywrap_core import Uri, Wrapper
from .abc.resolver_with_history import IResolverWithHistory

class WrapperResolver(IResolverWithHistory):
    __slots__ = ...
    uri: Uri
    wrapper: Wrapper
    def __init__(self, uri: Uri, wrapper: Wrapper) -> None:
        ...
    
    def get_step_description(self) -> str:
        ...
    


