"""
This type stub file was generated by pyright.
"""

from typing import Optional

BufferPointer = ...
def read_bytes(memory_pointer: BufferPointer, memory_length: int, offset: Optional[int] = ..., length: Optional[int] = ...) -> bytearray:
    ...

def read_string(memory_pointer: BufferPointer, memory_length: int, offset: int, length: int) -> str:
    ...

def write_string(memory_pointer: BufferPointer, memory_length: int, value: str, value_offset: int) -> None:
    ...

def write_bytes(memory_pointer: BufferPointer, memory_length: int, value: bytes, value_offset: int) -> None:
    ...

def mem_cpy(memory_pointer: BufferPointer, memory_length: int, value: bytearray, value_length: int, value_offset: int) -> None:
    ...

