"""
This type stub file was generated by pyright.
"""

class WasmAbortError(RuntimeError):
    def __init__(self, message: str) -> None:
        ...
    


class ExportNotFoundError(Exception):
    """raises when an export isn't found in the wasm module"""
    ...


