"""
This type stub file was generated by pyright.
"""

from typing import Union
from polywrap_core import GetFileOptions, IFileReader, InvocableResult, InvokeOptions, Invoker, Wrapper
from polywrap_manifest import AnyWrapManifest
from polywrap_result import Result
from wasmtime import Store
from .types.state import State

class WasmWrapper(Wrapper):
    file_reader: IFileReader
    wasm_module: bytes
    manifest: AnyWrapManifest
    def __init__(self, file_reader: IFileReader, wasm_module: bytes, manifest: AnyWrapManifest) -> None:
        ...
    
    def get_manifest(self) -> Result[AnyWrapManifest]:
        ...
    
    def get_wasm_module(self) -> Result[bytes]:
        ...
    
    async def get_file(self, options: GetFileOptions) -> Result[Union[str, bytes]]:
        ...
    
    def create_wasm_instance(self, store: Store, state: State, invoker: Invoker): # -> Instance | None:
        ...
    
    async def invoke(self, options: InvokeOptions, invoker: Invoker) -> Result[InvocableResult]:
        ...
    


