"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Optional, TYPE_CHECKING
from polywrap_result import Result
from .uri import Uri
from .uri_package_wrapper import UriPackageOrWrapper

if TYPE_CHECKING:
    ...
@dataclass(slots=True, kw_only=True)
class IUriResolutionStep:
    source_uri: Uri
    result: Result[UriPackageOrWrapper]
    description: Optional[str] = ...
    sub_history: Optional[List[IUriResolutionStep]] = ...


