"""
This type stub file was generated by pyright.
"""

from typing import Union
from .uri import Uri
from .wrap_package import IWrapPackage
from .wrapper import Wrapper

UriPackageOrWrapper = Union[Uri, Wrapper, IWrapPackage]
