"""
This type stub file was generated by pyright.
"""

from typing import List
from polywrap_core import IUriResolutionStep

def get_uri_resolution_path(history: List[IUriResolutionStep]) -> List[IUriResolutionStep]:
    ...

