"""
This type stub file was generated by pyright.
"""

from typing import Optional
from polywrap_core import IUriResolver
from ..types import UriResolverLike

def resolver_like_to_resolver(resolver_like: UriResolverLike, resolver_name: Optional[str] = ...) -> IUriResolver:
    ...

