"""
This type stub file was generated by pyright.
"""

from typing import Any
from polywrap_core import Invoker, InvokerOptions
from polywrap_result import Result
from unsync import unsync
from wasmtime import Instance, Memory, Store
from .types.state import State

@unsync
async def unsync_invoke(invoker: Invoker, options: InvokerOptions) -> Result[Any]:
    ...

def create_memory(store: Store, module: bytes) -> Memory:
    ...

def create_instance(store: Store, module: bytes, state: State, invoker: Invoker) -> Instance:
    ...

