"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from polywrap_core import GetManifestOptions, IFileReader, IWasmPackage, Wrapper
from polywrap_manifest import AnyWrapManifest
from polywrap_result import Result

class WasmPackage(IWasmPackage):
    file_reader: IFileReader
    manifest: Optional[Union[bytes, AnyWrapManifest]]
    wasm_module: Optional[bytes]
    def __init__(self, file_reader: IFileReader, manifest: Optional[Union[bytes, AnyWrapManifest]] = ..., wasm_module: Optional[bytes] = ...) -> None:
        ...
    
    async def get_manifest(self, options: Optional[GetManifestOptions] = ...) -> Result[AnyWrapManifest]:
        ...
    
    async def get_wasm_module(self) -> Result[bytes]:
        ...
    
    async def create_wrapper(self) -> Result[Wrapper]:
        ...
    


