"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from polywrap_core import Client, IUriResolutionContext, IUriResolver, Uri

class IResolverWithHistory(IUriResolver, ABC):
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext): # -> Result[UriPackageOrWrapper]:
        ...
    
    @abstractmethod
    def get_step_description(self) -> str:
        ...
    


