"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import List
from polywrap_core import Client, IUriResolutionContext, IUriResolver, Uri, UriPackageOrWrapper
from polywrap_result import Result

class IUriResolverAggregator(IUriResolver, ABC):
    @abstractmethod
    async def get_uri_resolvers(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[List[IUriResolver]]:
        ...
    
    @abstractmethod
    def get_step_description(self) -> str:
        ...
    
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[UriPackageOrWrapper]:
        ...
    
    async def try_resolve_uri_with_resolvers(self, uri: Uri, client: Client, resolvers: List[IUriResolver], resolution_context: IUriResolutionContext) -> Result[UriPackageOrWrapper]:
        ...
    


