"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from polywrap_core import Client, IUriResolutionContext, IUriResolver, Uri, UriPackageOrWrapper
from polywrap_manifest import DeserializeManifestOptions
from polywrap_result import Result
from .wrapper_cache_interface import IWrapperCache

class CacheResolverOptions:
    deserialize_manifest_options: DeserializeManifestOptions
    end_on_redirect: Optional[bool]
    ...


class PackageToWrapperCacheResolver:
    __slots__ = ...
    name: str
    resolver_to_cache: IUriResolver
    cache: IWrapperCache
    options: CacheResolverOptions
    def __init__(self, resolver_to_cache: IUriResolver, cache: IWrapperCache, options: CacheResolverOptions) -> None:
        ...
    
    def get_options(self) -> Any:
        ...
    
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[UriPackageOrWrapper]:
        ...
    


