"""
This type stub file was generated by pyright.
"""

from typing import Dict, Union
from polywrap_core import Uri, Wrapper
from .wrapper_cache_interface import IWrapperCache

class WrapperCache(IWrapperCache):
    map: Dict[Uri, Wrapper]
    def __init__(self) -> None:
        ...
    
    def get(self, uri: Uri) -> Union[Wrapper, None]:
        ...
    
    def set(self, uri: Uri, wrapper: Wrapper) -> None:
        ...
    


