"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, List, Optional, TypedDict

class RawInvokeResult(TypedDict):
    result: Optional[bytes]
    error: Optional[str]
    ...


class RawSubinvokeResult(TypedDict):
    result: Optional[bytes]
    error: Optional[str]
    args: List[Any]
    ...


class RawSubinvokeImplementationResult(TypedDict):
    result: Optional[bytes]
    error: Optional[str]
    args: List[Any]
    ...


@dataclass(kw_only=True, slots=True)
class State:
    invoke: RawInvokeResult = ...
    subinvoke: RawSubinvokeResult = ...
    subinvoke_implementation: RawSubinvokeImplementationResult = ...
    get_implementations_result: Optional[bytes] = ...
    method: Optional[str] = ...
    args: Optional[bytes] = ...
    env: Optional[bytes] = ...


