"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Union
from ..types import Client, Uri

def get_env_from_uri_history(uri_history: List[Uri], client: Client) -> Union[Dict[str, Any], None]:
    ...

