"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional, TYPE_CHECKING
from result import Result
from .uri import Uri
from .uri_package_wrapper import UriPackageOrWrapper

if TYPE_CHECKING:
    ...
@dataclass(slots=True, kw_only=True)
class IUriResolutionStep:
    source_uri: Uri
    result: Result[UriPackageOrWrapper, Exception]
    description: Optional[str] = ...
    sub_history: Optional[IUriResolutionStep] = ...


