"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from .wrapper import Wrapper

class IWasmPackage(ABC):
    @abstractmethod
    def create_wrapper(self) -> Wrapper:
        ...
    


