from enum import Enum
from msgpack.ext import ExtType
from polywrap_result import Result as Result
from typing import Any

class ExtensionTypes(Enum):
    GENERIC_MAP: int

def encode_ext_hook(obj: Any) -> ExtType: ...
def decode_ext_hook(code: int, data: bytes) -> Any: ...
def sanitize(value: Any) -> Any: ...
def msgpack_encode(value: Any) -> Result[bytes]: ...
def msgpack_decode(val: bytes) -> Result[Any]: ...
