from typing import MutableMapping, TypeVar

K = TypeVar('K')
V = TypeVar('V')

class GenericMap(MutableMapping[K, V]):
    def __init__(self, _map: MutableMapping[K, V]) -> None: ...
    def has(self, key: K) -> bool: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
