"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from ..types import Client, Env, Uri

def get_env_from_uri_history(uri_history: List[Uri], client: Client) -> Union[Env, None]:
    ...

