"""
This type stub file was generated by pyright.
"""

from typing import Dict
from polywrap_core import Client, IFileReader, IUriResolutionContext, IUriResolver, Uri, UriPackageOrWrapper
from polywrap_result import Result
from .fs_resolver import FsUriResolver
from .redirect_resolver import RedirectUriResolver

class BaseUriResolver(IUriResolver):
    _fs_resolver: FsUriResolver
    _redirect_resolver: RedirectUriResolver
    def __init__(self, file_reader: IFileReader, redirects: Dict[Uri, Uri]) -> None:
        ...
    
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[UriPackageOrWrapper]:
        ...
    


