"""
This type stub file was generated by pyright.
"""

from polywrap_core import Client, IFileReader, IUriResolutionContext, IUriResolver, Uri, UriPackageOrWrapper
from polywrap_result import Result

class SimpleFileReader(IFileReader):
    async def read_file(self, file_path: str) -> Result[bytes]:
        ...
    


class FsUriResolver(IUriResolver):
    file_reader: IFileReader
    def __init__(self, file_reader: IFileReader) -> None:
        ...
    
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[UriPackageOrWrapper]:
        ...
    


