"""
This type stub file was generated by pyright.
"""

from typing import Dict
from polywrap_core import Client, IUriResolutionContext, IUriResolver, Uri
from polywrap_result import Result

class RedirectUriResolver(IUriResolver):
    _redirects: Dict[Uri, Uri]
    def __init__(self, redirects: Dict[Uri, Uri]) -> None:
        ...
    
    async def try_resolve_uri(self, uri: Uri, client: Client, resolution_context: IUriResolutionContext) -> Result[Uri]:
        ...
    


